
name: alpha
on :
  push :
    branches: alpha

jobs :
  get:
    outputs :
      workflow_files: ${{ steps.workflow_files.outputs.files }}
      workflow_names: ${{ steps.workflow_names.outputs.names }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: workflow_files
        run: |
          WORKFLOWS=$(ls .github/workflows | grep Module)
          for WORKFLOW in $WORKFLOWS ; do
            NAME=$(echo $WORKFLOW | sed 's/\(\S\+\).yml/\1/')
            NAMES="$NAMES $NAME"
          done;
          NAMES=$(sed 's/\s\+/\n/g' <<< $NAMES)
          output=$(echo $NAMES | jq -R '[.]' | jq -s -c 'add')
          echo "::set-output name=files::$output"
      - run: echo ${{ steps.workflow_files.outputs.files }}
      - id: workflow_names
        run: |
          WORKFLOWS=$(ls .github/workflows | grep Module)
          for WORKFLOW in $WORKFLOWS ; do
            NAME=$(cat .github/workflows/$WORKFLOW | grep -G '^name :' | sed 's/name\s*:\s\+\(\S*\)/\1/')
            NAMES="$NAMES $NAME"
          done;
          echo "::set-output name=names::$NAMES"
      - run : echo ${{ steps.workflow_names.outputs.names }}

  test :
    needs : get
    runs-on : ubuntu-latest
    steps :
      - run : echo ${{ needs.get.outputs.workflow_files }}
      - run: echo ${{ needs.get.outputs.workflow_names }}
  # test :
  #   needs : get
  #   uses : dmvict/CiCdTemplate/.github/workflows/Exp.yml@alpha
  #   with :
  #     matrix : '{ "modules" : ${{ needs.get.outputs.workflow_files }} }'
  #     modules : ${{ needs.get.outputs.workflow_names }}

