
name : auto_pr_to_alpha

on :
  push :
    branches :
      - '*'
      - '*/*'
      - '**'
      - '!master'
      - '!main'
      - '!alpha'
      - '!beta'

jobs :

  forward :
    uses : dmvict/CiCdTemplate/.github/workflows/AutoPr.yml@workflow
    with :
      src_branch : '${{ github.ref_name }}'
      dst_branch : 'alpha'
    secrets :
      PRIVATE_GITHUB_BOT_TOKEN : '${{ secrets.PRIVATE_GITHUB_BOT_TOKEN }}'
